### ISSUE TITLE
Balancing the smoke demon

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#380]
While I was working on #378 I made some tweaks to the smoke demon to make it a little more powerful. I wonder if this was a mistake, now that I realize my changes to the damage system were actually just restoring Kerkerkruip 9's behaviour.

Damage to the smoke demon depends on its concentration. Originally, the damage was:

concentration 0: no change
concentration 1: +25% 
concentration 2: +50%
concentration 3: +75%
concentration 4: +100%

Hey, I just realized that's like the robe of the dead mage! Anyway, I reduced these numbers to:

concentration 0: -25%
concentration 1: no change
concentration 2: +25%
concentration 3: +50%
concentration 4: +75%

I think I'll probably change them back, but maybe I'll run some fight tests and play around a little first.

**Comment by VictorGijsbers** [comment]
Hi Mike. I don't really understand... you say you made the demon a little more powerful, but if I look at the table, it seems less powerful?

With the smoke demon, we have to realise that the chance to encounter it is independent of your level. The demon should be a big threat to level 0 players, but easily disposable by players who have absorbed a lot of powers. (And it should be especially threatening in the elemental plane of smoke.) It doesn't need to be especially tough to kill, since it can reform; but you shouldn't be able to just ignore its attacks.

**Comment by mciul** [comment]
It's been a while, but I think the only changes I made are the ones described in the ticket - I changed the density damage multiplier and then changed it back.

**Comment by VictorGijsbers** [comment]
I think this issue can be closed. Smoke demon is back where it was, seems to function well. Reopen or make a new issue if it seems unbalanced in play.
